### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by Frodo-Dev** [DragonCat4012/BarChart#1]
Hi DragonCat4012,
thx a lot for this small chart. I thing there is a small bug in the drawAxe. I thing it must be like this.
 drawAxe(0.0, "\(maxValue)")
        //1/2 line
        drawAxe((0.25 * zeroLineValue), "\(0.75 * maxValue)")
        //1/4 line
        drawAxe((0.5 * zeroLineValue), "\(0.5 * maxValue)")
        //3/4 line
        drawAxe((0.75 * zeroLineValue), "\(0.25 * maxValue)")

Kind regards Mark

**Comment by DragonCat4012** [comment]
oh right>.>
